### ISSUE TITLE
JetBrains Mono より italic の傾斜が著しく大きい

### ISSUE THREAD

**Issue by kobi32768** [kb10uy/MomiageMono#5]
# Actual
[JetBrains Mono](https://www.jetbrains.com/lp/mono/) では italic の傾斜角度は垂直を基準として右回りに 9° とされているが Momiage Mono では実測値で約 30° ほど傾いている。
なお、MomiageMono Nerd Font でも同様の挙動である。

![image](https://github.com/kb10uy/MomiageMono/assets/40712426/6577e02b-4b08-4353-a46b-5c189705ccf6)

# Expected 
Momiage Mono でも JetBrains Mono 同様に 9° の傾斜となること

# Environment
- CLion 2023.2.2

**Comment by kb10uy** [comment]
新規に CLion をインストールしてフォントと Language Default > Keyword のところだけ変更して検証してみましたが再現しませんね……。

<img width="320" alt="clion64_1702149538_tmgLE" src="https://github.com/kb10uy/MomiageMono/assets/2630080/b5a4bfe0-d74b-4f2f-8d1b-ad9d201573da"><br>
<img width="320" alt="clion64_1702149565_dmH3q" src="https://github.com/kb10uy/MomiageMono/assets/2630080/bc50aa72-9d3e-48e6-95af-bf7b27e8e006"><br>
<img width="500" alt="clion64_1702149551_HKDZm" src="https://github.com/kb10uy/MomiageMono/assets/2630080/6694d234-5677-474c-9464-1e87bda98739"><br>

(Italic の有無だけでなく Bold の有無も含めて全部インストールしないと正しく Italic の存在が判定されないみたな可能性はありそう)

**Comment by kobi32768** [comment]
念のため 全てのユーザにインストール を 8 つの *.ttf 全てに行いましたが全て上書きするか聞かれた上変わらずですね……
他の JetBrains IDE (少なくとも IntelliJ CE, CLion Nova) でも起こっているようです

VSCode で確認したところ JetBrains Mono に近いのでこっちの JB IDE の設定に起因しているように思えますが心当たりがないですね……
![image](https://github.com/kb10uy/MomiageMono/assets/40712426/15d68ead-3d4b-4cbd-9848-0927209a5d7c)

**Comment by kobi32768** [comment]
Main weight を Bold にしてみたところ Bold Italic は正常っぽいです

**Comment by kobi32768** [comment]
MomiageMono Nerd Font にすると今度は Bold Italic が異常で Italic が正常になるようです
また、Windows 11 の Explorer のプレビューでは立体になっていることから Windows 側の解釈がおかしくなっているのかも……？
![image](https://github.com/kb10uy/MomiageMono/assets/40712426/d2f90ffc-9542-46b8-b609-146ffa698675)

**Comment by kobi32768** [comment]
原因は不明ですが Windows 再起動で直りました
お騒がせしました……
インストールしたあと再起動はしてるはずなんですが……

**Comment by kb10uy** [comment]
こちらで検証進めたところ **Nerd Font あり版となし版をの片方だけをインストールした状態にする**と発生しなくなったんですが、root cause は結局謎ですね……。

FontForge で設定する何らかのプロパティーの値がミスってそうな気配はしますが一旦 close で

補足: 2019.2 時代から italic に oblique がかかる現象はあったらしい ([Font in editor incorrect (always italics)](https://youtrack.jetbrains.com/issue/JBR-1778/Font-in-editor-incorrect-always-italics))
